### ISSUE TITLE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (24576x80 and 16x64)

### ISSUE THREAD

**Issue by yerlyx** [NUSTM/HIMT#4]
I use  bert-base-uncased  as bert_model(run_himt.sh) .
Running the program encountered this error
RuntimeError: mat1 and mat2 shapes cannot be multiplied (24576x80 and 16x64)
could you give some advice? any suggestion will be appreciated
<img width="859" alt="2" src="https://user-images.githubusercontent.com/81076087/231995729-390f89e7-8569-493d-87a0-d82f5745f9bf.png">

**Comment by EmilyCodeSailor** [comment]
I  have encountered the same issue as well, did you manage to resolve it?

**Comment by yerlyx** [comment]
> 

![076f855992480c657ce83df238a1dbe](https://github.com/NUSTM/HIMT/assets/81076087/e76ae2f2-836b-4340-9bc0-8c121bd910ff)
just change the " self.Wr = nn.Linear(80,64)"

**Comment by EmilyCodeSailor** [comment]
Thank you very much.
