### ISSUE TITLE
怎么解决RuntimeError: mat1 dim 1 must match mat2 dim 0

### ISSUE THREAD

**Issue by haxin3696** [NUSTM/HIMT#9]
![image](https://github.com/user-attachments/assets/eb093a24-698c-4b2b-b9e3-623697208e7c)
运行bash run_himy.sh报错，显示权重不匹配，请问有人遇到过同样的问题吗？有人知道要怎么解决吗？

**Comment by AvalonSama** [comment]
不同数据集的wr参数有些区别，可以具体将两个矩阵的形状打出来看一下
